spring:
  datasource:
    username: root
    password: abcd1234
    url: jdbc:mysql://localhost:3306/jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    ime-between-eviction-runs-millis: 3000000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
